name: Build

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Build application
        run: python build.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebButtonWatcher-${{ matrix.os }}${{ matrix.os == 'windows-latest' && '.zip' || '.dmg' }}
          path: dist/WebButtonWatcher-${{ matrix.os }}${{ matrix.os == 'windows-latest' && '.zip' || '.dmg' }}
