name: Release

on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  # Wait for test workflow to complete
  wait-for-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5 # Add timeout
    outputs:
      should_release: ${{ steps.check.outputs.should_release }}
    steps:
      - uses: actions/checkout@v4

      - name: Sleep for 10 seconds
        run: sleep 10

      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        id: wait-for-test
        with:
          ref: ${{ github.ref }}
          check-name: "test"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
        continue-on-error: true

      - id: check
        run: |
          # Always proceed with release for now
          echo "should_release=true" >> $GITHUB_OUTPUT

  build-and-release:
    needs: wait-for-tests
    if: always() # Run even if wait-for-tests times out
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            artifact_name: WebButtonWatcher-macOS.dmg
            asset_name: WebButtonWatcher-macOS.dmg
          - os: windows-latest
            artifact_name: WebButtonWatcher-Windows.zip
            asset_name: WebButtonWatcher-Windows.zip

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Verify Version
        id: verify_version
        shell: python
        run: |
          import os
          import sys
          import re
          from web_button_watcher import __version__

          # Get tag version from GitHub ref
          tag_version = os.environ['GITHUB_REF'].split('/')[-1][1:]  # Remove 'v' prefix
          print(f"Package version: {__version__}")
          print(f"Tag version: {tag_version}")

          # Set output for later steps
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
              f.write(f"version={__version__}\n")

          if __version__ != tag_version:
              print(f"Error: Version mismatch! Tag version ({tag_version}) doesn't match package version ({__version__})")
              sys.exit(1)

          print("Version verification successful!")

      - name: Build application
        run: python build.py

      - name: Import Developer Certificate (macOS)
        if: matrix.os == 'macos-latest'
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.MACOS_CERTIFICATE }}
          P12_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          KEYCHAIN_PASSWORD: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
        run: |
          # Create keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain

          # Import certificate
          echo $BUILD_CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain

          # Remove certificate file
          rm certificate.p12

      - name: Sign and Notarize App (macOS)
        if: matrix.os == 'macos-latest'
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          # Sign the app
          codesign --force --options runtime --sign "Developer ID Application: $APPLE_TEAM_ID" dist/WebButtonWatcher.app --deep

          # Create DMG
          hdiutil create -volname "WebButtonWatcher" -srcfolder dist/WebButtonWatcher.app -ov -format UDZO dist/WebButtonWatcher-macOS.dmg

          # Sign DMG
          codesign --force --sign "Developer ID Application: $APPLE_TEAM_ID" dist/WebButtonWatcher-macOS.dmg

          # Notarize
          xcrun notarytool submit dist/WebButtonWatcher-macOS.dmg --apple-id "$APPLE_ID" --password "$APPLE_PASSWORD" --team-id "$APPLE_TEAM_ID" --wait

          # Staple the notarization ticket
          xcrun stapler staple dist/WebButtonWatcher-macOS.dmg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          files: dist/${{ matrix.artifact_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
