name: Release

on:
  push:
    tags:
      - "v*" # Trigger on version tags

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            artifact_name: WebButtonWatcher-macOS.dmg
            asset_name: WebButtonWatcher-macOS.dmg
          - os: windows-latest
            artifact_name: WebButtonWatcher-Windows.zip
            asset_name: WebButtonWatcher-Windows.zip

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Verify Version
        id: verify_version
        run: |
          VERSION=$(python -c "from web_button_watcher import __version__; print(__version__)")
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          if [ "$VERSION" != "$TAG_VERSION" ]; then
            echo "Error: Version mismatch! Tag version ($TAG_VERSION) doesn't match package version ($VERSION)"
            exit 1
          fi

      - name: Build application
        run: python build.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          files: dist/${{ matrix.artifact_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
