name: Release

on:
  push:
    branches: [main]

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            artifact_name: WebButtonWatcher-macOS.dmg
            asset_name: WebButtonWatcher-macOS.dmg
          - os: windows-latest
            artifact_name: WebButtonWatcher-Windows.zip
            asset_name: WebButtonWatcher-Windows.zip

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Build application
        run: python build.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: success() && github.ref == 'refs/heads/main'
        with:
          files: dist/${{ matrix.artifact_name }}
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
