name: Release

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches: [main]

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  build-and-release:
    # Only run if the test workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            artifact_name: WebButtonWatcher-macOS.dmg
            asset_name: WebButtonWatcher-macOS.dmg
          - os: windows-latest
            artifact_name: WebButtonWatcher-Windows.zip
            asset_name: WebButtonWatcher-Windows.zip

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(python -c "from web_button_watcher import __version__; print(__version__)")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build application
        run: python build.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          files: dist/${{ matrix.artifact_name }}
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
