name: Tests

on:
  push:
    branches: [main]
    tags:
      # Only match tags like v1.0 or v2.1, not patch versions like v1.0.1
      - "v[0-9]+.[0-9]"
      - "v[0-9]+.[0-9].[0]"
  pull_request:
    branches: [main]

jobs:
  fast-test:
    if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Run tests
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          pytest -v --capture=no
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: larsniet/web-button-watcher
          files: ./coverage.xml
          fail_ci_if_error: false

  full-test:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Chrome (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
      - name: Install Chrome (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install --cask chromium chromedriver
      - name: Install Chrome (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install chromium chromedriver
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Run tests
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          pytest -v --capture=no
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: larsniet/web-button-watcher
          files: ./coverage.xml
          fail_ci_if_error: false
